version: '3.9'
services:
  # client:
  # build: client
  # ports:
  #   - "3000:3000"
  eventbus:
    build: server/eventbus
    ports:
      - "4000:4000"
  deliveries:
    build: server/deliveries
    ports:
      - "4001:4001"
    depends_on:
      - eventbus
  drivers:
    build: server/drivers
    ports:
      - "4002:4002"
    depends_on:
      - eventbus
  cart:
    build: server/cart
    ports:
      - "4003:4003"
    depends_on:
      - eventbus
  favorites:
    build: server/favorites
    ports:
      - "4004:4004"
    depends_on:
      - eventbus
  metrics:
    build: server/metrics
    ports:
      - "4005:4005"
    depends_on:
      - eventbus
    environment:
      DATABASE_URL: mongodb+srv://Befake:VTcs9nXYICf08QlU@cluster0.alqzhxc.mongodb.net/?retryWrites=true&w=majority
  notifications:
    build: server/notifications
    ports:
      - "4006:4006"
    depends_on:
      - eventbus
  pickups:
    build: server/pickups
    ports:
      - "4007:4007"
    depends_on:
      - eventbus
  restaurants:
    build: server/restaurants
    ports:
      - "4008:4008"
    depends_on:
      - eventbus
    environment:
      DATABASE_URL: mongodb+srv://Befake:woJ3lbTZLYnlYgay@cluster0.pmskj9f.mongodb.net/?retryWrites=true&w=majority
  review-comments:
    build: server/review-comments
    ports:
      - "4009:4009"
    depends_on:
      - eventbus
  reviews:
    build: server/reviews
    ports:
      - "4010:4010"
    depends_on:
      - eventbus
  users:
    build: server/users
    ports:
      - "4011:4011"
    depends_on:
      - eventbus
    environment:
      DATABASE_URL: mongodb+srv://Befake:6a4rWhYjq4bReM94@cluster0.kf7533j.mongodb.net/?retryWrites=true&w=majority
  wallet:
    build: server/wallet
    ports:
      - "4012:4012"
    depends_on:
      - eventbus
